### PR TITLE
Theme alerts

### PR DESCRIPTION
**Pull request by timja**
Fixes https://github.com/jenkinsci/dark-theme-plugin/issues/98
Fixes https://github.com/jenkinsci/dark-theme-plugin/issues/102

Requires: https://github.com/jenkinsci/jenkins/pull/4842

<details>
<summary>Before</summary>

image

Screenshot

</details>

<details>
<summary>After</summary>

image

image

</details>

Thoughts?

### CODE REVIEW

**Comment by daniel-beck** [comment]
These background colors are very saturated, IMO too much.

**Comment by timja** [comment]
Will have more of a play unless anyone has any ideas, the background colours came from: https://mdbootstrap.com/live/_doc/all-colors.html

text colours were experimentation to get sufficient contrast

**Comment by timja** [comment]
What about the alerts from: https://bootswatch.com/darkly/

**Comment by timja** [comment]
image

**Comment by timja** [comment]
image

**Comment by fqueiruga** [comment]
I think that any text over a bright alert background will be difficult to read. Not sure if those background colors are the right choice. I know the former ones looked bad, but they weren't too bright, which is the point of the dark-theme

**Comment by daniel-beck** [comment]
> I know the former ones looked bad, but they weren't too bright

I thought they were very bright, hence #102. I didn't enjoy seeing these alerts in a dark room when I tried the theme. HSB is 0°/8%/95% and 50°/10%/99% respectively. They can barely be any brighter, it's basically "off-white".

**Comment by timja** [comment]
WDYT of the second attempt @daniel-beck ?

the current ones are definitely too bright

**Comment by daniel-beck** [comment]
How would the original PR state here look like with white text for a direct comparison to the second version?

**Comment by timja** [comment]
Original with white text:

image

**Comment by timja** [comment]
I think what's here is better than current, merging and can iterate.

**Comment by daniel-beck** [comment]
> Original with white text:

FWIW I think that looks great, at least in this block of alerts.

Also all of the red backgrounds clash with the button color, creating a weird contrast effect (chromostereopsis?).

**Comment by timja** [comment]
Will adjust to original with white hopefully later today

**Comment by timja** [comment]
^^ https://github.com/jenkinsci/dark-theme-plugin/pull/121

**Pull request merged**
