### PR TITLE
Improve hyperlink contrast

### PR DESCRIPTION
**Pull request by VirtualTim**
<details><summary>Before</summary>

before-logs
before-tests
</details>

<details><summary>After</summary>

after-logs
after-tests
</details>

It would also be nice to fix the grey on pink, but I couldn't tell off the top of my head how to.

### CODE REVIEW

**Comment by VirtualTim** [comment]
@timja, you've been changing similar things, what do you think about this?

**Comment by timja** [comment]
The screenshots look the same to me?

Once https://github.com/jenkinsci/pipeline-stage-view-plugin/pull/104 is released we can fix this by changing the colour from pink to be something else.

I was planning to change it to the same colour as the danger notifications

**Comment by VirtualTim** [comment]
Alt-tab between them. The difference is fairly subtly, but I find one much easier on the eyes.

**Comment by timja** [comment]
ah right, any chance of a couple more screenshots just to see what the rest of Jenkins looks like?
that does look better I agree

**Comment by VirtualTim** [comment]
I've added another set of screenshots.
I'm not sure how much more I could add without getting into trouble for revealing too much about our build system. But the theme seems to be using two main background colours, so I hope this is enough.

**Review by timja — APPROVED** [review]

**Comment by timja** [comment]
Thanks

**Comment by timja** [comment]
@allcontributors please add @VirtualTim for code

**Pull request merged**
