### PR TITLE
build: Use renovate for dependencies

### PR DESCRIPTION
**Pull request by NotMyFault**
Similar to core, I suggest we use renovate for dependencies too.

I attempted to modify its perms via https://github.com/apps/renovate/installations/new and GH reported a successful result but I'd be surprised if that worked out.

Oops, origin branch. Please delete afterwards

### CODE REVIEW

**Review by timja — APPROVED** [review]
It didn’t work but I’ve enabled it now

**Comment by timja** [comment]
Ah I did have an email to approve it

**Comment by NotMyFault** [comment]
TIL renovate can update your plugin files 👀 https://github.com/jenkinsci/dark-theme-plugin/pull/222

**Comment by timja** [comment]
> TIL renovate can update your plugin files 👀 #222

yup, https://github.com/hmcts/cnp-jenkins-docker/pulls?q=is%3Apr+sort%3Aupdated-desc+is%3Aclosed+author%3Aapp%2Frenovate

**Pull request merged**
